---
# handlers file for ansible-role-kibana

- name: Restart kibana
  service:
    name: "{{ kibana_service_name }}"
    state: restarted
  notify: Wait for kibana to start

- name: Wait for kibana to start
  wait_for:
    host: localhost
    port: "{{ kibana_config_merged['server.port'] }}"
